<a href="https://colab.research.google.com/github/Sunday-Ogunya/Machine_Learning-Assignmrent-Task/blob/main/Untitled4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
pd.read_excel("CPI New.xlsx", header=2)

,Year,Months,All ItemsMonthly,12-Month Average(All Items,All Items Month-on change (%),All Items Year-on change (%),All Items 12-Month average change (%),Food Monthly,Food 12-Month Average,Food Month-on change (%),Food Year-on change (%),Food 12-Month average change (%),ALL ITEMS LESS FARM PRODUCE AND ENERGY,Monthly,12-Month Average,Month-on change (%),Year-on change (%),12-Month average change (%)
0,2009,Jan,90.152714,86.023683,0.545228,14.034158,12.031652,89.459773,84.602751,0.920695,18.435754,16.535991,NaN,92.562497,87.826286,0.914118,12.591287,7.642901
1,2009,Feb,90.827824,86.987072,0.748851,14.584435,12.566778,90.215627,85.857872,0.844910,20.040723,17.453982,NaN,92.645308,88.470231,0.089465,9.099774,7.869328
2,2009,Mar,91.363255,87.943477,0.589502,14.366476,13.101404,90.943659,86.916300,0.806990,16.233035,17.742332,NaN,93.137001,89.501061,0.530726,15.315604,9.249714
3,2009,Apr,91.898687,88.840519,0.586047,13.267531,13.509682,91.620682,87.931834,0.744442,15.341506,17.889949,NaN,94.063454,90.421907,0.994721,13.311304,10.240837
4,2009,May,93.593444,89.750753,1.844158,13.212435,13.787065,93.498725,88.991421,2.049803,15.739625,17.949059,NaN,95.419492,91.310836,1.441620,12.586260,10.980871
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,2024,July,767.375919,675.197878,2.275627,33.395252,30.757097,966.781324,836.536653,2.472027,39.534250,36.361487,NaN,590.118784,527.557351,2.159888,27.465023,24.646268
187,2024,August,784.379628,691.100188,2.215825,32.150132,31.258308,989.693586,859.039570,2.369953,37.522655,36.991917,NaN,603.515874,538.430516,2.270236,27.582988,25.180030
188,2024,September,804.141820,707.611856,2.519468,32.696276,31.730506,1015.805007,882.247298,2.638334,37.771342,37.532477,NaN,616.182787,549.482975,2.098853,27.428106,25.639622
189,2024,October,825.368076,725.016461,2.639616,33.876872,32.255573,1045.644539,906.766869,2.937526,39.157713,38.123370,NaN,629.355046,561.073279,2.137719,28.368704,26.119802
190,2024,November,847.142110,743.162863,2.638100,34.598334,32.771514,1076.837352,932.371570,2.983118,39.925160,38.674240,NaN,640.894082,572.998315,1.833470,28.746938,26.640538

In [15]:
import pandas as pd

# Load CPI data, skipping the title and sub-header rows
cpi = pd.read_excel("CPI New.xlsx", sheet_name="Sheet2", header=2)

In [16]:
print(cpi.columns.tolist())

['Year', 'Months', 'All ItemsMonthly', '12-Month Average(All Items', 'All Items Month-on change (%)', 'All Items Year-on change (%)', 'All Items 12-Month average change (%)', 'Food Monthly', 'Food 12-Month Average', 'Food Month-on change (%)', 'Food Year-on change (%)', 'Food 12-Month average change (%)', 'ALL ITEMS LESS FARM PRODUCE AND ENERGY', 'Monthly', '12-Month Average', 'Month-on change (%)', 'Year-on change (%)', '12-Month average change (%)']

In [24]:
cpi = cpi[['all_itemsmonthly',  # CPI Index
    'all_items_month-on_change_(%)',  # Monthly inflation
    'all_items_year-on_change_(%)',   # Yearly inflation
    'food_monthly',
    'food_month-on_change_(%)',
    'food_year-on_change_(%)',
    'all_items_less_farm_produce_and_energy',
    'month-on_change_(%)',  # Core CPI monthly
    'year-on_change_(%)'    # Core CPI yearly
]].rename(columns={
    'all_itemsmonthly': 'cpi_index',
    'all_items_month-on_change_(%)': 'cpi_mom',
    'all_items_year-on_change_(%)': 'cpi_yoy',
    'food_monthly': 'food_index',
    'food_month-on_change_(%)': 'food_mom',
    'food_year-on_change_(%)': 'food_yoy',
    'all_items_less_farm_produce_and_energy': 'core_index',
    'month-on_change_(%)': 'core_mom',
    'year-on_change_(%)': 'core_yoy'
})

KeyError: "None of [Index(['all_itemsmonthly', 'all_items_month-on_change_(%)',\n       'all_items_year-on_change_(%)', 'food_monthly',\n       'food_month-on_change_(%)', 'food_year-on_change_(%)',\n       'all_items_less_farm_produce_and_energy', 'month-on_change_(%)',\n       'year-on_change_(%)'],\n      dtype='object')] are in the [columns]"

In [25]:
import pandas as pd

# Load CPI data, skipping the title and sub-header rows
cpi = pd.read_excel("CPI New.xlsx", sheet_name="Sheet2", header=2)

# Clean column names
cpi.columns = cpi.columns.str.strip().str.lower().str.replace(' ', '_')

# Print the column names after cleaning to verify
print(cpi.columns.tolist())

# Now, select and rename columns based on the verified column names
cpi = cpi[['all_itemsmonthly',  # CPI Index
    'all_items_month-on_change_(%)',  # Monthly inflation
    'all_items_year-on_change_(%)',   # Yearly inflation
    'food_monthly',
    'food_month-on_change_(%)',
    'food_year-on_change_(%)',
    'all_items_less_farm_produce_and_energy',
    'month-on_change_(%)',  # Core CPI monthly
    'year-on_change_(%)'    # Core CPI yearly
]].rename(columns={
    'all_itemsmonthly': 'cpi_index',
    'all_items_month-on_change_(%)': 'cpi_mom',
    'all_items_year-on_change_(%)': 'cpi_yoy',
    'food_monthly': 'food_index',
    'food_month-on_change_(%)': 'food_mom',
    'food_year-on_change_(%)': 'food_yoy',
    'all_items_less_farm_produce_and_energy': 'core_index',
    'month-on_change_(%)': 'core_mom',
    'year-on_change_(%)': 'core_yoy'
})

['year', 'months', 'all_itemsmonthly', '12-month_average(all_items', 'all_items_month-on_change_(%)', 'all_items_year-on_change_(%)', 'all_items_12-month_average_change_(%)', 'food_monthly', 'food_12-month_average', 'food_month-on_change_(%)', 'food_year-on_change_(%)', 'food_12-month_average_change_(%)', 'all_items_less_farm_produce_and_energy', 'monthly', '12-month_average', 'month-on_change_(%)', 'year-on_change_(%)', '12-month_average_change_(%)']